version: '3'
services:
  db_postgres_examples:
    image: postgres:11
    environment:
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: root
      POSTGRES_DB: examples
    volumes:
      - postgresql:/var/lib/postgresql
      - postgres11-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgresql:
  postgres11-data:
    driver: local
